[book]
authors = ["Caido"]
language = "en"
multilingual = false
src = "src"
title = "Caido Documentation"

[output.html]
default-theme = "navy"
git-repository-url = "https://github.com/caido/documentation"
